// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":return img`
.....6feeeeeeeeeef6.....
....6776eeeeeeeee676....
...6777666eeee6667776...
..6776ee67777777667776..
...668ee7768867788666...
......ee77eeee67ee......
......ee6eeeeee6ce......
......eefeeeeeeece......
......eeceeeeeeece......
......eeceeeeeeefe......
......eeceeeeeeefe......
......eeeeeeeeeefe......
......eeeeeeeeeece......
.....6eeeeeeeeeece6.....
....6776eeeeeeeee676....
...6776666eeee6766776...
..6776ee77777777667776..
...668ce7768867788666...
......ce77eeee67ee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......eeeeeeeeeeee......
......beeeeeeeeeeb......
.......beeeeeeeeb.......
........beeeeeeb........
........................
........................
........................
`;
            case "image2":return img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f 2 f . . . 
. . . f f e e e e f 2 2 2 f . . 
. . . f e e e f f e e e e f . . 
. . . f f f f e e 2 2 2 2 e f . 
. . . f e 2 2 2 f f f f e 2 f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e e e d d d f . . . 
. . . . . f 4 d d e 4 e f . . . 
. . . . . f e d d e 2 2 f . . . 
. . . . f f f e e f 5 5 f f . . 
. . . . f f f f f f f f f f . . 
. . . . . f f . . . f f f . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
